### ISSUE TITLE
Issue with live stream

### ISSUE THREAD

**Issue by sbidy** [themasch/node-ebml#8]
Hey,

I tried to decode a mkv live stream. But i get a exception:

Error: Unrepresentable value: 01ffffffffffffff at Object.tools.readVint C:\Projects\StreamJS\StreamJS\lib\tools.js:23:27)
    at EbmlDecoder.readSize (C:\Projects\StreamJS\StreamJS\lib\decoder.js:112:22)
    at EbmlDecoder._write (C:\Projects\StreamJS\StreamJS\lib\decoder.js:44:49)
    at doWrite (_stream_writable.js:221:10)
    at writeOrBuffer (_stream_writable.js:211:5)
    at EbmlDecoder.Writable.write (_stream_writable.js:180:11)
    at checkDataForIdent (C:\Projects\StreamJS\StreamJS\app.js:100:17)
    at IncomingMessage.<anonymous> (C:\Projects\StreamJS\StreamJS\app.js:28:17)
    at IncomingMessage.EventEmitter.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (_stream_readable.js:746:14)

Can somebody help :question: 

Thanks!

**Comment by themasch** [comment]
should be fixed by #10. If not, please reopen.

**Comment by vhmth** [comment]
I've commented [here](https://github.com/themasch/node-ebml/pull/10#issuecomment-292350172), but I think that this is still an issue if `length > 8` in `readVint`. I've run into this case a couple of times - not sure how we should handle it. I'd be game for:

* Transitioning to [node-bigint](https://github.com/substack/node-bigint)
* Figuring out a way to "ignore" that read and just keep parsing

I'm not sure how the latter would work, but it seems like less work and I'd be game for that. If I can get some guidance on either solution, I'd be happy to take a crack at it and get it implemented ASAP.

**Comment by vhmth** [comment]
Left y'all a video on my thoughts:

https://www.useloom.com/share/af250d7f718248aca456fe0225107f89

Right now I'm playing around with returning `length: 8` in the case where it's `> 8` in `readVint`.

**Comment by roccomuso** [comment]
I got the error again:
```
Error: Unrepresentable length: 9 0008128065d3030024 
node_modules/ebml/lib/ebml/tools.js:10:19
```

Wasn't this fixed?

**Comment by themasch** [comment]
@roccomuso, @vhmth I (finally, just a few years late) created a tracking issue for this. Its over there: #34

**Comment by bradisbell** [comment]
@themasch The unknown length/live streaming case is a special value.  I'd suggest that whether or not you support bigint, the unknown length case be treated separately if possible.

**Comment by themasch** [comment]
@bradisbell oh sure. The `unknown length` requires special treatment.  IIRC We currently return a (-1) [1] but I guess we should add another field to that struct to indicate if its a known, defined value or an unknown value. 


[^1] (https://github.com/themasch/node-ebml/blob/master/lib/ebml/tools.js#L33)

**Comment by hem1232** [comment]
Hello,

i am facing below issue while making blob seekable.

ERROR Error: Unrepresentable length: 9 000000000000000000
    at Object.readVint (vendor.js:341444)
    at EBMLDecoder.push../node_modules/ts-ebml/lib/EBMLDecoder.js.EBMLDecoder.readTag (vendor.js:340014)
    at EBMLDecoder.push../node_modules/ts-ebml/lib/EBMLDecoder.js.EBMLDecoder.readChunk (vendor.js:339985)
    at EBMLDecoder.push../node_modules/ts-ebml/lib/EBMLDecoder.js.EBMLDecoder.decode (vendor.js:339975)
    at MultipartUploadService.getSeekableWebmBlob (main.js:4606)
    at MultipartUploadService.saveVideo (main.js:4592)
    at ConnectionsInfo.stopCall (main.js:18020)
    at RemoteSupportComponent.stopCallActionHandle (main.js:19154)
    at Object.eval [as handleEvent] (RemoteSupportComponent.html:167)
    at handleEvent (vendor.js:91424)

can anyone help me with this on priority.

Thanks,
Hemant c

**Comment by hem1232** [comment]
> I got the error again:
> 
> ```
> Error: Unrepresentable length: 9 0008128065d3030024 
> node_modules/ebml/lib/ebml/tools.js:10:19
> ```
> 
> Wasn't this fixed?

did you get any solution on above issue??

**Comment by lr-mjaouen** [comment]
I'm having the same issue but only on safari

**Comment by soorajlv** [comment]
I am also having the same issue on Google Chrome and FireFox.

**Screenshot**
![image](https://user-images.githubusercontent.com/12485276/235466842-283804e3-fb63-4272-b208-c7563fefdc11.png)
**Code Sample**

```
const handleDownload = React.useCallback(() => {
    if (recordedChunks.length) {
		const elms = decoder.decode(recordedChunks);
		elms.forEach((elm)=>{ reader.read(elm); });
		reader.stop()
		const refinedMetadataBuf = tools.makeMetadataSeekable(reader.metadatas, reader.duration, reader.cues);
		const body = recordedChunks.slice(reader.metadataSize);
		const blob = new Blob([refinedMetadataBuf, body], {type: "video/webm"});
		const url = URL.createObjectURL(blob);
      
      const a = document.createElement("a");
      document.body.appendChild(a);
      a.style = "display: none";
      a.href = url;
      a.download = "react-webcam-stream-capture.webm";
      a.click();
      window.URL.revokeObjectURL(url);
      setRecordedChunks([]);
    }
  }, [recordedChunks]);
```
Any idea how to fix this?
